2019-06-04 16:37:36,457 ERROR - [ ConnectionLocator.getConnection() ]R1客户端通过数据源【java:comp/env/ResourceOne/DataSource】获取数据库连接失败        
org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory ([jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1225)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at com.icss.resourceone.sdk.connection.ConnectionLocator.getConnection(ConnectionLocator.java:106)
	at com.icss.resourceone.sdk.init.InitR1ClientHandler.doInitClient(InitR1ClientHandler.java:93)
	at com.icss.resourceone.sdk.init.InitR1ClientHandler.initLocalContext(InitR1ClientHandler.java:157)
	at com.icss.resourceone.sdk.framework.Context.getInstance(Context.java:106)
	at com.icss.ro.framework.agent.manager.ClientManager.getStatusFromDB(ClientManager.java:485)
	at com.icss.ro.framework.agent.manager.ClientManager.init(ClientManager.java:105)
	at com.icss.ro.framework.agent.manager.ClientManager.<init>(ClientManager.java:77)
	at com.icss.ro.framework.agent.manager.ClientManager.getInstance(ClientManager.java:120)
	at com.icss.resourceone.sdk.SdkFilter.doFilter(SdkFilter.java:122)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at com.icss.j2ee.servlet.filter.ChangeReqEncoding.doFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:174)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:874)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.ibm.db2.jcc.b.gm: [jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001
	at com.ibm.db2.jcc.b.wc.a(wc.java:536)
	at com.ibm.db2.jcc.b.wc.a(wc.java:259)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:354)
	at com.ibm.db2.jcc.t4.xb.<init>(xb.java:73)
	at com.ibm.db2.jcc.t4.a.w(a.java:261)
	at com.ibm.db2.jcc.t4.b.a(b.java:1774)
	at com.ibm.db2.jcc.b.eb.a(eb.java:451)
	at com.ibm.db2.jcc.b.eb.<init>(eb.java:417)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:295)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:193)
	at org.apache.tomcat.dbcp.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1247)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1221)
	... 27 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at com.ibm.db2.jcc.t4.y.run(y.java:34)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:348)
	... 38 more
2019-06-04 16:37:46,758 ERROR - [ ConnectionLocator.getConnection() ]R1客户端通过数据源【java:comp/env/ResourceOne/DataSource】获取数据库连接失败        
org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory ([jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1225)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at com.icss.resourceone.sdk.connection.ConnectionLocator.getConnection(ConnectionLocator.java:106)
	at com.icss.resourceone.sdk.framework.Context.getDbConnection(Context.java:263)
	at com.icss.ro.framework.agent.manager.ClientManager.getStatusFromDB(ClientManager.java:486)
	at com.icss.ro.framework.agent.manager.ClientManager.init(ClientManager.java:105)
	at com.icss.ro.framework.agent.manager.ClientManager.<init>(ClientManager.java:77)
	at com.icss.ro.framework.agent.manager.ClientManager.getInstance(ClientManager.java:120)
	at com.icss.resourceone.sdk.SdkFilter.doFilter(SdkFilter.java:122)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at com.icss.j2ee.servlet.filter.ChangeReqEncoding.doFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:174)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:874)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.ibm.db2.jcc.b.gm: [jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001
	at com.ibm.db2.jcc.b.wc.a(wc.java:536)
	at com.ibm.db2.jcc.b.wc.a(wc.java:259)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:354)
	at com.ibm.db2.jcc.t4.xb.<init>(xb.java:73)
	at com.ibm.db2.jcc.t4.a.w(a.java:261)
	at com.ibm.db2.jcc.t4.b.a(b.java:1774)
	at com.ibm.db2.jcc.b.eb.a(eb.java:451)
	at com.ibm.db2.jcc.b.eb.<init>(eb.java:417)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:295)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:193)
	at org.apache.tomcat.dbcp.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1247)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1221)
	... 25 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at com.ibm.db2.jcc.t4.y.run(y.java:34)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:348)
	... 36 more
2019-06-04 16:37:57,730 ERROR - [ ConnectionLocator.getConnection() ]R1客户端通过数据源【java:comp/env/ResourceOne/DataSource】获取数据库连接失败        
org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory ([jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1225)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at com.icss.resourceone.sdk.connection.ConnectionLocator.getConnection(ConnectionLocator.java:106)
	at com.icss.resourceone.sdk.framework.Context.getDbConnection(Context.java:263)
	at com.icss.ro.framework.agent.manager.ClientManager.getStatusFromDB(ClientManager.java:486)
	at com.icss.ro.framework.agent.manager.ClientManager.init(ClientManager.java:105)
	at com.icss.ro.framework.agent.manager.ClientManager.<init>(ClientManager.java:77)
	at com.icss.ro.framework.agent.manager.ClientManager.getInstance(ClientManager.java:120)
	at com.icss.resourceone.sdk.SdkFilter.doFilter(SdkFilter.java:122)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at com.icss.j2ee.servlet.filter.ChangeReqEncoding.doFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:174)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:874)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.ibm.db2.jcc.b.gm: [jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001
	at com.ibm.db2.jcc.b.wc.a(wc.java:536)
	at com.ibm.db2.jcc.b.wc.a(wc.java:259)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:354)
	at com.ibm.db2.jcc.t4.xb.<init>(xb.java:73)
	at com.ibm.db2.jcc.t4.a.w(a.java:261)
	at com.ibm.db2.jcc.t4.b.a(b.java:1774)
	at com.ibm.db2.jcc.b.eb.a(eb.java:451)
	at com.ibm.db2.jcc.b.eb.<init>(eb.java:417)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:295)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:193)
	at org.apache.tomcat.dbcp.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1247)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1221)
	... 25 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at com.ibm.db2.jcc.t4.y.run(y.java:34)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:348)
	... 36 more
2019-06-04 16:38:28,127 ERROR - [ ConnectionLocator.getConnection() ]R1客户端通过数据源【java:comp/env/ResourceOne/DataSource】获取数据库连接失败        
org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory ([jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1225)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at com.icss.resourceone.sdk.connection.ConnectionLocator.getConnection(ConnectionLocator.java:106)
	at com.icss.resourceone.sdk.framework.Context.getDbConnection(Context.java:263)
	at com.icss.ro.framework.agent.manager.ClientManager.getStatusFromDB(ClientManager.java:486)
	at com.icss.ro.framework.agent.manager.ClientManager.init(ClientManager.java:105)
	at com.icss.ro.framework.agent.manager.ClientManager.<init>(ClientManager.java:77)
	at com.icss.ro.framework.agent.manager.ClientManager.getInstance(ClientManager.java:120)
	at com.icss.resourceone.sdk.SdkFilter.doFilter(SdkFilter.java:122)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at com.icss.j2ee.servlet.filter.ChangeReqEncoding.doFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:174)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:874)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.ibm.db2.jcc.b.gm: [jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001
	at com.ibm.db2.jcc.b.wc.a(wc.java:536)
	at com.ibm.db2.jcc.b.wc.a(wc.java:259)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:354)
	at com.ibm.db2.jcc.t4.xb.<init>(xb.java:73)
	at com.ibm.db2.jcc.t4.a.w(a.java:261)
	at com.ibm.db2.jcc.t4.b.a(b.java:1774)
	at com.ibm.db2.jcc.b.eb.a(eb.java:451)
	at com.ibm.db2.jcc.b.eb.<init>(eb.java:417)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:295)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:193)
	at org.apache.tomcat.dbcp.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1247)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1221)
	... 25 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at com.ibm.db2.jcc.t4.y.run(y.java:34)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:348)
	... 36 more
2019-06-04 16:38:38,612 ERROR - [ ConnectionLocator.getConnection() ]R1客户端通过数据源【java:comp/env/ResourceOne/DataSource】获取数据库连接失败        
org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory ([jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1225)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at com.icss.resourceone.sdk.connection.ConnectionLocator.getConnection(ConnectionLocator.java:106)
	at com.icss.resourceone.sdk.framework.Context.getDbConnection(Context.java:263)
	at com.icss.ro.framework.agent.manager.ClientManager.getStatusFromDB(ClientManager.java:486)
	at com.icss.ro.framework.agent.manager.ClientManager.init(ClientManager.java:105)
	at com.icss.ro.framework.agent.manager.ClientManager.<init>(ClientManager.java:77)
	at com.icss.ro.framework.agent.manager.ClientManager.getInstance(ClientManager.java:120)
	at com.icss.resourceone.sdk.SdkFilter.doFilter(SdkFilter.java:122)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at com.icss.j2ee.servlet.filter.ChangeReqEncoding.doFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:174)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:874)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.ibm.db2.jcc.b.gm: [jcc][t4][2043][11550][3.50.148] 异常 java.net.ConnectException：打开端口 50,000 上服务器 /10.100.7.244 的套接字时出错，消息为：Connection refused: connect。 ERRORCODE=-4296, SQLSTATE=08001
	at com.ibm.db2.jcc.b.wc.a(wc.java:536)
	at com.ibm.db2.jcc.b.wc.a(wc.java:259)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:354)
	at com.ibm.db2.jcc.t4.xb.<init>(xb.java:73)
	at com.ibm.db2.jcc.t4.a.w(a.java:261)
	at com.ibm.db2.jcc.t4.b.a(b.java:1774)
	at com.ibm.db2.jcc.b.eb.a(eb.java:451)
	at com.ibm.db2.jcc.b.eb.<init>(eb.java:417)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:295)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:193)
	at org.apache.tomcat.dbcp.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1247)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1221)
	... 25 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at com.ibm.db2.jcc.t4.y.run(y.java:34)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.ibm.db2.jcc.t4.xb.a(xb.java:348)
	... 36 more
2019-06-11 11:11:13,442 ERROR - [ ConnectionLocator.getConnection() ]R1客户端通过数据源【java:comp/env/ResourceOne/DataSource】获取数据库连接失败        
java.lang.NullPointerException
	at com.icss.resourceone.sdk.connection.ConnectionLocator.getConnection(ConnectionLocator.java:108)
	at com.icss.resourceone.sdk.framework.Context.getDbConnection(Context.java:264)
	at com.icss.resourceone.sdk.SdkSignOn.performLogin(SdkSignOn.java:114)
	at com.icss.j2ee.login.LoginHandler.login(Unknown Source)
	at com.icss.resourceone.sso.agent.SSOR1Agent.sdkLogin(SSOR1Agent.java:438)
	at com.icss.resourceone.sso.agent.SSOR1Agent.login(SSOR1Agent.java:420)
	at com.icss.resourceone.sso.client.SSOClient.doFilter(SSOClient.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at com.chinasofti.ro.bizframework.core.web.filter.LocaleFilter.doFilterInternal(Unknown Source)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at com.icss.regieapp.common.filter.RedirectUrlFilter.doFilter(RedirectUrlFilter.java:121)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at com.chinasofti.ro.bizframework.core.web.filter.InitialFilter.doFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:174)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:874)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
	at java.lang.Thread.run(Thread.java:662)
